apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: "{{ app }}"
  namespace: "{{ team }}"
  labels:
    team: "{{ team }}"
spec:
  image: "{{ image }}"
  port: 8080
  startup:
    path: /isalive
    initialDelay: 10
    failureThreshold: 6
    periodSeconds: 5
    timeout: 1
  liveness:
    path: /isalive
    failureThreshold: 6
    periodSeconds: 10
  readiness:
    path: /isready
    failureThreshold: 3
    periodSeconds: 10
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 20m
      memory: 256Mi
  secureLogs:
    enabled: true
  filesFrom:
    - secret: serviceuser-srvdp-speider
      mountPath: "/var/run/secrets/nais.io/service_user"
  envFrom:
    - configmap: kafka-bootstrap-servers
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: dp-speider-v1
    - name: KAFKA_RAPID_TOPIC
      value: teamdagpenger.rapid.v1
  kafka:
    pool: "{{ kafka_pool }}"
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
